update workflows to make versioning fixed snapshot.

diff --git a/.github/workflows/maven-lib-release.yml b/.github/workflows/maven-lib-release.yml
--- a/.github/workflows/maven-lib-release.yml
+++ b/.github/workflows/maven-lib-release.yml
@@ -1,4 +1,3 @@
-# Note: default release notes file is docs/release.md.
 name: Release and deploy to Central
 
 on: workflow_dispatch
@@ -6,7 +5,7 @@ on: workflow_dispatch
 jobs:
   release-checks:
     runs-on: ubuntu-latest
-    container: zepben/pipeline-basic:5.0.0
+    container: zepben/pipeline-basic:5.5.0
     env:
       NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
       NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
@@ -20,17 +19,14 @@ jobs:
       - name: Release checks and update version for release
         run: |
           /scripts/release-checks.sh --java --maven pom.xml
-          FILE=docs/release.md
-          if [ -f "$FILE" ]; then
-            export release_date=$(date +'%d %B %Y')
-            /scripts/finalize-version.sh --java --maven pom.xml $FILE 'sed -i -e "s/TBD/$release_date/g"'
-          else
-            /scripts/finalize-version.sh --java --maven pom.xml
-          fi
+          /scripts/finalize-version.sh --java --maven pom.xml
         shell: bash
   deploy-central:
     needs: release-checks
     runs-on: ubuntu-latest
+    outputs:
+      artifact: ${{ steps.build.outputs.artifact }}
+      version: ${{ steps.build.outputs.version }}
     container: zepben/pipeline-java
     steps:
       - uses: actions/checkout@v2
@@ -59,12 +55,37 @@ jobs:
           GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
         continue-on-error: true
 
-      - name: Merge and Tag
+      - name: Upload coverage to Codecov
         if: steps.build.outcome == 'success'
+        uses: codecov/codecov-action@v1
+
+      - uses: actions/upload-artifact@master
+        if: steps.build.outcome == 'success'
+        with:
+          name: ${{ steps.build.outputs.artifact }}
+          path: ${{ steps.build.outputs.artifact-path }}
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the mvn deploy command above."
+          exit 1
+        shell: bash
+
+  create-release:
+    needs: [deploy-central, build-docs]
+    runs-on: ubuntu-latest
+    container: zepben/pipeline-basic:5.0.0
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Merge and Tag
         id: merge
         run: | 
-          git checkout ${GITHUB_REF/refs\/heads\//}
-          git merge release
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git merge origin/release
           git push origin ${GITHUB_REF/refs\/heads\//}
           artifactId=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/artifactId")
           version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
@@ -75,9 +96,17 @@ jobs:
           echo "::set-output name=artifact::$(echo $artifact)"
           echo "::set-output name=artifact-path::$(echo target/$artifact)"
         shell: bash
+        continue-on-error: true
+
+      - name: Fail
+        if: steps.merge.outcome == 'failure'
+        run: | 
+          git push origin -d release
+          echo "There was an error in merging the branch. release branch was deleted."
+          exit 1
+        shell: bash
 
       - name: Create Release
-        if: steps.build.outcome == 'success'
         id: create_release
         uses: actions/create-release@v1
         env:
@@ -85,33 +114,30 @@ jobs:
         with:
           tag_name: ${{ steps.merge.outputs.tag }}
           release_name: ${{ steps.merge.outputs.tag }}
-          body_path: docs/release.md
+          body_path: changelog.md
           draft: false
           prerelease: false
 
+      - name: Download binary
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ needs.deploy-central.outputs.artifact }}
+          path: built-artifacts
+
       - name: Upload Release Asset
-        if: steps.build.outcome == 'success'
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ steps.merge.outputs.artifact-path }}
-          asset_name: ${{ steps.merge.outputs.artifact }}
+          asset_path: built-artifacts/${{ needs.deploy-central.outputs.artifact }}
+          asset_name: ${{ needs.deploy-central.outputs.artifact }}
           asset_content_type: application/zip
 
-      - name: Fail build
-        if: steps.build.outcome == 'failure'
-        run: | 
-          git push origin -d release
-          echo "There was an error in the mvn deploy command above."
-          exit 1
-        shell: bash
-
   update-version:
-    needs: deploy-central
+    needs: create-release
     runs-on: ubuntu-latest
-    container: zepben/pipeline-basic:5.0.0
+    container: zepben/pipeline-basic:5.5.0
     env:
       NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
       NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
@@ -124,11 +150,5 @@ jobs:
       - uses: actions/checkout@v2
       - name: Update to next minor version
         run: |
-          FILE=docs/release.md
-          if [ -f "$FILE" ]; then
-            export ln=$(cat $FILE | grep -n "### v[0-9]\+.[0-9]\+.[0-9]\+" | head -1 | cut -d':' -f1)
-            /scripts/update-version.sh --java --maven --release pom.xml $FILE 'next_release_version=${version//-SNAPSHOT/} && sed -i "${ln}i \#\#\# v${version//-SNAPSHOT/}\n\n\#\#\#\#\# Breaking Changes\n\* None.\n\n\#\#\#\#\# New Features\n\* None.\n\n\#\#\#\#\# Enhancements\n\* None.\n\n\#\#\#\#\# Fixes\n\* None.\n\n\#\#\#\#\# Notes\n\* None.\n\n\-\-\-\n" $changelog && sed -i "5i \|\[${next_release_version}\]\(\#v${next_release_version//\./}\)\| \`TBD\` \|"'
-          else
-            /scripts/update-version.sh --java --maven --release pom.xml
-          fi
+          /scripts/update-version.sh --java --maven --release pom.xml changelog.md
         shell: bash
